/**
 * 错误码 — 镜像后端 ErrorCode 枚举
 * 用于前端类型安全的错误匹配：err.is(ERROR_CODE.STOCK_INSUFFICIENT)
 */

export const ERROR_CODE = {
  // User Domain (1xxx)
  USER_NOT_FOUND: 'USER_1001',
  USER_ALREADY_EXISTS: 'USER_1002',
  INVALID_CREDENTIALS: 'USER_1003',
  TOKEN_EXPIRED: 'USER_1004',
  TOKEN_REVOKED: 'USER_1005',
  PASSWORD_TOO_WEAK: 'USER_1006',
  EMAIL_NOT_VERIFIED: 'USER_1007',
  ADDRESS_LIMIT: 'USER_1008',

  // Product Domain (2xxx)
  PRODUCT_NOT_FOUND: 'PRODUCT_2001',
  SKU_NOT_FOUND: 'PRODUCT_2002',
  STOCK_INSUFFICIENT: 'PRODUCT_2003',
  CATEGORY_NOT_FOUND: 'PRODUCT_2004',
  DUPLICATE_SKU_CODE: 'PRODUCT_2005',
  INVALID_PRICE: 'PRODUCT_2006',
  PRODUCT_UNAVAILABLE: 'PRODUCT_2007',

  // Cart Domain (3xxx)
  CART_ITEM_NOT_FOUND: 'CART_3001',
  CART_LIMIT_EXCEEDED: 'CART_3002',
  CART_SKU_UNAVAILABLE: 'CART_3003',
  CART_PRICE_CHANGED: 'CART_3004',

  // Order Domain (4xxx)
  ORDER_NOT_FOUND: 'ORDER_4001',
  ORDER_STATUS_INVALID: 'ORDER_4002',
  ORDER_EXPIRED: 'ORDER_4003',
  ORDER_ALREADY_PAID: 'ORDER_4004',
  ORDER_CANCEL_DENIED: 'ORDER_4005',
  PAYMENT_FAILED: 'ORDER_4006',
  IDEMPOTENT_CONFLICT: 'ORDER_4007',

  // Gateway (9xxx)
  RATE_LIMITED: 'GATEWAY_9001',
  SERVICE_UNAVAILABLE: 'GATEWAY_9002',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
